In [1]:
import pandas as pd 
import numpy as np

In [11]:
ROS_PATH = 'D:\\Run Analysis\\BLOB_STORAGE\\Roster\\weekly_roster_processed\\31th_2021.xlsx'
PAY_PATH = 'D:\\Run Analysis\\BLOB_STORAGE\\Drivers_pay\\31th_2021.xlsx'

df_ros  = pd.read_excel(ROS_PATH)
df_pay = pd.read_excel(PAY_PATH)

df_RLI = df_ros[df_ros.Primary_route.eq('RLI')]

RLI_drivers = df_RLI.Primary_employeeID.unique()

In [13]:
RLI_related_df = df_ros[df_ros.Primary_employeeID.isin(RLI_drivers) | df_ros.Secondary_employeeID.isin(RLI_drivers)]
RLI_related_df.sort_values(by='Primary_employeeID')

,Date,Run_type,Primary_employeeID,Secondary_employeeID,Primary_driver_Name,Secondary_Driver_Name,Primary_route,Satellite_Route_1,Satellite_Route_2,Primary_truck,Alternative_Truck,Subcontracted_From/Special_Client,Note
32,2021-08-04,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,HYG,RL5,RL6/RLP,CF 71 JM,NaN,NaN,NaN
33,2021-08-06,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,HYG,DOY,RL5/RL6,CF 71 JM,NaN,NaN,NaN
63,2021-08-09,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,RL5,NaN,NaN,CF 71 JM,NaN,NaN,NaN
84,2021-08-10,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,RLD,NaN,NaN,XN 65 IJ,NaN,NaN,NaN
105,2021-08-05,DAY RUNS,ir02,swansgia,JOHNNY,GENE,RLI,NaN,NaN,XN 23 KQ,NaN,NaN,NaN
104,2021-08-10,DAY RUNS,swansgia,NaN,GENE ANSELMO,NaN,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN
6,2021-08-08,DAY RUNS,swlocbra,NaN,BRAD LOCKE,NaN,BR1,NaN,NaN,XN 80 YD,NaN,NaN,NaN
19,2021-08-10,DAY RUNS,swlocbra,NaN,BRAD LOCKE,NaN,FL2,NaN,NaN,XN 52 IJ,NaN,NaN,NaN
100,2021-08-04,DAY RUNS,swlocbra,swansgia,BRAD,GENE,RLI,NaN,NaN,XN 23 KQ,NaN,NaN,NaN
101,2021-08-06,DAY RUNS,swlocbra,swansgia,BRAD,GENE,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN
102,2021-08-09,DAY RUNS,swlocbra,swansgia,BRAD,GENE,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN
103,2021-08-07,DAY RUNS,swlocbra,swansgia,GENE,BRAD,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN

In [15]:
RLI_related_df
# df_1 = df.groupby(['Primary_employeeID','Primary_route']).agg({'Run_type' : 'count'}).reset_index().rename(columns={'Run_type' : 'occurrence'})     
# df_1['total'] = df_1.groupby('Primary_employeeID')['occurrence'].cumsum()
# df_1['portion'] = df_1.occurrence / df_1.groupby('Primary_employeeID')['total'].transform(np.max)

,Date,Run_type,Primary_employeeID,Secondary_employeeID,Primary_driver_Name,Secondary_Driver_Name,Primary_route,Satellite_Route_1,Satellite_Route_2,Primary_truck,Alternative_Truck,Subcontracted_From/Special_Client,Note
6,2021-08-08,DAY RUNS,swlocbra,NaN,BRAD LOCKE,NaN,BR1,NaN,NaN,XN 80 YD,NaN,NaN,NaN
19,2021-08-10,DAY RUNS,swlocbra,NaN,BRAD LOCKE,NaN,FL2,NaN,NaN,XN 52 IJ,NaN,NaN,NaN
32,2021-08-04,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,HYG,RL5,RL6/RLP,CF 71 JM,NaN,NaN,NaN
33,2021-08-06,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,HYG,DOY,RL5/RL6,CF 71 JM,NaN,NaN,NaN
63,2021-08-09,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,RL5,NaN,NaN,CF 71 JM,NaN,NaN,NaN
84,2021-08-10,DAY RUNS,ir02,NaN,JOHNNY RUHR,NaN,RLD,NaN,NaN,XN 65 IJ,NaN,NaN,NaN
100,2021-08-04,DAY RUNS,swlocbra,swansgia,BRAD,GENE,RLI,NaN,NaN,XN 23 KQ,NaN,NaN,NaN
101,2021-08-06,DAY RUNS,swlocbra,swansgia,BRAD,GENE,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN
102,2021-08-09,DAY RUNS,swlocbra,swansgia,BRAD,GENE,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN
103,2021-08-07,DAY RUNS,swlocbra,swansgia,GENE,BRAD,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN
104,2021-08-10,DAY RUNS,swansgia,NaN,GENE ANSELMO,NaN,RLI,NaN,NaN,XN 80 YD,NaN,NaN,NaN
105,2021-08-05,DAY RUNS,ir02,swansgia,JOHNNY,GENE,RLI,NaN,NaN,XN 23 KQ,NaN,NaN,NaN