In [15]:
import pandas as pd
import numpy as np
import re
general_waste_route = ['BR1','BR2',
                       'BR3','DOY',
                       'FL2','FLG',
                       'RL1','RL2',
                       'RL4','RL7',
                       'RL9','RLD',
                       'RLE','RLH',
                       'RLI','RLJ',
                       'RLK','SWG']

cardboard_route = ['FLP','HYG','RED','RL5','RL6','RL8','RLP','RLR','SWP']
Comingled_route = ['CBK','RLC','RLG']
subContractor = ['ALLMED','BIN',
                    'CKG','CLN',
                    'GRACE','JJR',
                    'OWE','REM',
                    'REP','REQ',
                    'RRNW','RRR',
                    'SHR','SPD',
                    'SUE','URM',
                    'VEO','VEOACT',
                    'VTG']
UOS = ['UOSCB','UOSCO','UOSGW','CMDCB','CMDGW','CUMCB','CUMGW','NEPGW']

In [16]:
def split_weekday(route_num : str):
    weekday = route_num.split('-')[1]
    return weekday

def clean_route_number(route_num : str):
#     match dash => -  and then . 
    cleaned_route_num = re.sub(r'-.', '',route_num)
    return cleaned_route_num

In [31]:
df = pd.read_csv("../df_test1.csv")
df['weekday'] = df['Route number'].apply(split_weekday)
df['Route number'] = df['Route number'].apply(clean_route_number)

In [80]:
df['Date_index'] = pd.to_datetime(df['Date'],format='%d/%m/%Y')
df = df.set_index(pd.DatetimeIndex(df['Date_index']))
df.sort_values(by=['Date'], inplace=True, ascending=False)

In [81]:
# From this point general_waste_route only
df = df[df['Route number'].isin(general_waste_route)]

In [82]:
# total_general_waste_rev = df['Price'].sum()
df

,Date,Customer Name,Address 1,City,State,PostCode,Qty Scheduled,Qty Serviced,Serv Type,Bin Volume,Status,Truck number,Route number,Waste Type,Price,weekday,Date_index
Date_index,,,,,,,,,,,,,,,,,
2020-12-22,2020-12-22,Beacon Lighting,367 Princes Hwy,Carlton,NSW,2218.0,1,1,COL,1.10,C,XN13KR,RLI,General Waste,56.36,2,2020-12-22
2020-12-22,2020-12-22,Agriculture House,195 Macquarie Street,Sydney,NSW,2000.0,12,12,COL,0.05,C,CJ65PS,BR2,General Waste,76.53,2,2020-12-22
2020-12-22,2020-12-22,Style Patisserie,9/1-3 Exell St,Banksmeadow,NSW,2019.0,1,1,COL,0.24,C,XN19IN,RLH,General Waste,23.29,2,2020-12-22
2020-12-22,2020-12-22,The Centennial Homestead,Grand Drive,Centennial Park,NSW,2021.0,4,1,COL,0.24,C,CBB804,RL4,General Waste,27.96,2,2020-12-22
2020-12-22,2020-12-22,Cook & Archies,4-14 Buckingham St,Surry Hills,NSW,2010.0,1,1,COL,1.10,C,CL98LU,RLD,General Waste,48.40,2,2020-12-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,2020-12-02,Shankman Holdings,191 Clarence Street,Sydney,NSW,2000.0,7,3,COL,0.24,C,CJ65PS,BR2,Dry Waste,45.05,3,2020-12-02
2020-12-02,2020-12-02,Timeless Commercial Cleaning,85 McLachlan Ave,Darlinghurst,NSW,2010.0,1,1,COL,0.24,C,BY46TO,RL9,Comingle,16.78,3,2020-12-02
2020-12-02,2020-12-02,VCCP,Level 2/19 Foster St,Surry Hills,NSW,2010.0,1,1,FUT,0.24,F,CL98LU,RLD,Comingle,0.00,3,2020-12-02
2020-12-02,2020-12-02,Oracle - Rockdale Garden,3-7 Keats Avenue,Rockdale,NSW,2216.0,10,10,COL,0.24,C,XN13KR,RLI,General Waste,117.37,3,2020-12-02
2020-12-02,2020-12-02,Republic 2 - SP65530,50 Burton St,Darlinghurst,NSW,2010.0,2,2,COL,1.10,C,CBB804,RL4,General Waste,108.37,3,2020-12-02

In [73]:
# df['Date'] = pd.to_datetime(df['Date'],format='%d/%m/%Y')
# df = df.set_index(pd.DatetimeIndex(df['Date']))

# ==========================
# series = df.resample('7D')
# series_1 = series.get_group('2020-12-02')
# ==========================

# print(series_1.Price.sum())
# df.set_index('date').groupby('name')["ext price"].resample("M").sum()
# groupby('Route number')['Truck number']

# ================================
# ser_obj = series_1.groupby('Route number').Price.sum()
# ser_obj
# ================================

# ===========================================Extra==============
# Route name per Rev_type 

# Also Able to know what truck is driving each route

# ser_obj.get_group("FL2")["Truck number"].unique()
# for route_name in general_waste_route:
#     try:
#         print(route_name)
#         print(ser_obj.get_group(route_name)["Truck number"].unique())
#     except KeyError:
#         print(route_name)
# ===========================================

# set_index('Route number')['Truck number']

# series_1.groupby('Truck number').Price.sum()

Route number
BR1    21215.27
BR2    21561.78
BR3    18293.21
FL2    16435.83
FLG    31384.25
RL1    18861.88
RL2    17255.12
RL4    20632.62
RL7    19635.92
RL9    14268.23
RLD    27064.94
RLE    13758.80
RLH    13426.17
RLI    27022.83
RLJ    17341.20
RLK     3602.27
SWG    19507.57
Name: Price, dtype: float64