In [4]:
import pandas as pd
import numpy as np
import typing
df = pd.read_csv("../df_test1.csv")
df

,Date,Customer Name,Address 1,City,State,PostCode,Qty Scheduled,Qty Serviced,Serv Type,Bin Volume,Status,Truck number,Route number,Waste Type,Price
0,22/12/2020,Compounded Pty Ltd,Unit25/56 O'Riordan St,Alexandria,NSW,2015.0,1,2,COL,0.66,C,XN65IJ,RL6-2,Cardboard,11.00
1,22/12/2020,Lonergan Research Pty Ltd,263 Clarence St,Sydney,NSW,2000.0,1,1,FUT,0.24,F,XN97FC,RLC-2,Comingle,11.00
2,22/12/2020,MLH Pty Ltd,54 MacArthur St,Parramatta,NSW,2150.0,1,1,DE,0.66,C,CV50EC,BIN-2,General Waste,0.00
3,22/12/2020,Sign Up Now,3/3 Kelso Crescent,Moorebank,NSW,2170.0,1,1,COL,1.50,C,CM97HV,FLG-2,General Waste,108.46
4,22/12/2020,Suby Tech,30 Antoine St,Rydalmere,NSW,2116.0,1,1,FUT,0.66,F,XN23KQ,RL2-2,General Waste,13.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30278,2/12/2020,179 Hyde Investment Pty LTd,179 Elizabeth St,Sydney,NSW,2000.0,15,15,COL,0.24,C,CJ65PS,BR2-3,General Waste,0.00
30279,2/12/2020,Adina Apartment Hotel Sydney Airport,17 Bourke Rd,Mascot,NSW,2020.0,1,1,FUT,0.66,F,XN19IN,RLH-3,Comingle,11.00
30280,2/12/2020,Matteo Restaurant & Bar,29-33 Bay St,Double Bay,NSW,2028.0,4,2,COL,0.24,C,CBB804,RL4-3,Comingle,26.55
30281,2/12/2020,Republic 2 - SP65530,50 Burton St,Darlinghurst,NSW,2010.0,2,2,COL,1.10,C,CBB804,RL4-3,General Waste,108.37
30282,2/12/2020,WasteSpec - Kiaora Place,1 Kiaora Road,Double Bay,NSW,2028.0,2,2,COL,0.66,C,CBB804,RL4-3,Comingle,31.92